syntax on
set background=dark
" colorscheme monokai
set t_Co=256
highlight Comment cterm=bold
set autoindent
set smartindent
set clipboard=unnamed
filetype plugin indent on
" By default, tab and auto-indentation are 4
set tabstop=4 shiftwidth=4
set softtabstop=0 noexpandtab

set hlsearch
set backspace=start,eol,indent 
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
" For c files, set tabs to 2 and auto-indentation to 2
autocmd Filetype c setlocal ts=2 sw=2 expandtab

" Vundle settings starts
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'Yggdroot/indentLine'
Plugin 'jiangmiao/auto-pairs'
call vundle#end()
filetype plugin indent on
" Vundle setting ends

" F5 to run code
autocmd Filetype python nnoremap <F5> <Esc>:w<CR>:exec '!python' shellescape(@%, 1)<CR>
autocmd Filetype c nnoremap <F5> <Esc>:w<CR>:exec '!gcc % -o %:r && ./%:r'<CR>

" Remap for window functions
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-H> <C-W><C-H>
nnoremap <C-L> <C-W><C-L>

" YouCompleteMe
set completeopt-=preview
let g:ycm_path_to_python_interpreter='/usr/local/bin/python3.6'
let g:ycm_seed_identifiers_with_syntax=1
" let g:ycm_add_preview_to_completeopt = 0
" let g:ycm_autoclose_preview_window_after_completion = 1
" let g:ycm_autoclose_preview_window_after_insertion = 1

" Airline
" let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='wombat'

" IndentLine
let g:indentLine_char='¦'
autocmd Filetype python let g:indentLine_enabled=1
